docs/tephi/source/sphinxext/custom_class_autodoc.py
lib/tephi/__init__.py
lib/tephi/_constants.py
lib/tephi/isopleths.py
lib/tephi/tests/__init__.py
lib/tephi/tests/test_tephigram.py
lib/tephi/transforms.py

This PR is simple code hygiene to purge the use of `__future__` ... it has already arrived, thanks to Python3 :tada:  
@trexfeathers

remove the __future__

---

lib/tephi/tests/__init__.py
lib/tephi/tests/test_imagerepo.py

This PR adds test coverage to ensure the the `imagerepo.json` file contains URIs to images that are already available from `test-tephi-imagehash`.
@trexfeathers

test imagerepo

---

tephi/tests/__init__.py
tephi/tests/idiff.py
tephi/tests/test_imagerepo.py

This PR adds the `idiff` utility to help the `tephi` developer investigate failed graphical tests.
@trexfeathers

add idiff support

---

docs/tephi/source/conf.py

This PR makes the `tephi` package discoverable within the rtd builder environment.
@trexfeathers

fix doc build for rtd builder environment

---

README.md

This PR links the `tephi` logo to the `latest` rtd documentation.
@trexfeathers

fix logo url

---

MANIFEST.in
pyproject.toml
setup.py

This PR reinstates the `pytest-runner` to allow `python setup.py test` to work, and adds additional PyPI metadata.

update setup.py for pypi

---

README.md

This PR fixes the `binder` URL (typo)

fix binder url

---

ci/requirements/rtd.yml
docs/tephi/source/conf.py
requirements-dev.txt

This PR adds `sphinx-copybutton` support to the documentation.

add docs copybutton

---

README.md
setup.cfg
setup.py

The PR tidies the `setup.py`, moving all of the `metadata` into `setup.cfg`.
Note that, since `setuptools` [41.5.0](https://setuptools.readthedocs.io/en/latest/history.html#v41-5-0) ([PR #1878](https://github.com/pypa/setuptools/pull/1878)) the `test` option, and `test_suite` and `tests_require` keywords have been deprecated.

move to setup.cfg

---

pyproject.toml

This PR ensures that the non-legacy `setuptools` backend is used for building.

non-legacy backend

---

docs/tephi/source/customise.rst
docs/tephi/source/plotting.rst
setup.cfg
tephi/__init__.py

This PR fixes various doctest failures

fix doctests

---

.coveragerc
requirements.txt
tephi/__init__.py
tephi/utils/__init__.py
tephi/utils/report.py

This PR adds platform and package dependency reporting support. This will facilitate better support for user who raise issues, and allow them to easily reap a report of metadata that will help the developer assist them by providing some context to the users working environment.
For example,
```bash
>>> import tephi
>>> tephi.Report()
--------------------------------------------------------------------------------
Date: Fri May 29 15:13:49 2020 BST
OS : Linux
CPU(s) : 4
Machine : x86_64
Architecture : 64bit
Environment : Python
Python 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52)
[GCC 7.3.0]
tephi : 0.3.0.dev0
matplotlib : 3.2.1
numpy : 1.18.4
scipy : 1.4.1
IPython : 7.14.0
scooby : 0.5.4
-------------------------------------------------------------------------------- …
```

Add scooby

---

tephi/utils/report.py

This PR relaxes the need for the `scooby` package, making it a runtime optional package instead i.e., we don't actually need the `scooby` package for `tephi` to function properly.

optional scooby

---

setup.cfg
tephi/tests/__init__.py
tephi/tests/conftest.py
tephi/tests/test_imagerepo.py
tephi/tests/test_tephigram.py

This PR replaces the use of `unittest` with `pytest`.
@trexfeathers I'd like you to take the time to understand and actually review this PR.
It will be an ideal way to introduce you to the wonders of `pytest` :smile:

migrate unittest to pytest

---

tephi/__init__.py
tephi/tests/results/imagerepo.json

This PR fixes a bug resulting from porting from `py2` to `py3` involving true division instead of integer division.
This fix is required by users for the next release.
Note that there are expected image differences, so the https://github.com/SciTools/test-tephi-imagehash/pull/8 requires to be merged first before this PR will pass.

fix locator

---

tephi/isopleths.py

This PR fixes the [numpy 1.20.0 deprecation](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) for `numpy.object` i.e., avoids the following warning being generated:
```
tephi/isopleths.py:29
/tmp/persistent/itwl/git/tephi/tephi/isopleths.py:29: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
formats=("f4", "f4", "f4", np.object),
```

fix np.object deprecation

---

.github/workflows/manifest.yml
.github/workflows/test-docs.yml
.github/workflows/test.yml
MANIFEST.in
setup.cfg

This PR automates the task of PyPI manifest checking as part of our CI.
It also includes:
* rationalising the `MANIFEST.in`
* removing the `setuptools` deprecated use of `license` from `setup.cfg`, in favour of the recommended trove classifier, see [here](https://setuptools.pypa.io/en/latest/deprecated/distutils/setupscript.html?highlight=license#additional-meta-data)
* replacing the `setuptools` deprecated use of `license_file` for `license_files`, see [here](https://setuptools.pypa.io/en/latest/history.html?highlight=license_file#id348)

tidy and automate manifest check

---

tephi/isopleths.py

Closes #55.
Default zorder for plots has been changed to 4. 
Default zorder for barbs has been changed to 4.1, slightly above plot-lines. 
These were chosen based on the MatPlotLib defaults, see [here](https://matplotlib.org/stable/gallery/misc/zorder_demo.html).

Fix order of legend, so plot doesn't overlap

---

tephi/__init__.py
tephi/isopleths.py

- Docstrings updated to reference correct anchor order
- Also added consistency to "temperature - pressure pair" references to always be hyphenated.

Fix docstrings with incorrect anchor order

---

.github/workflows/ci-manifest.yml

This PR migrates the `ci-manifest` GHA to the `SciTools/workflows` reusable GHA.

adopt reusable ci-manifest gha

---

.readthedocs.yml

https://blog.readthedocs.com/use-build-os-config/
build.image has been deprecated, and was causing rtd build failures. This is fixed hopefully. 
I also compared the whole file with the one found in Iris, and seems generally up to date (and with less redundancy 👀).

replaced image with os in .rtd.yml build

---

.pre-commit-config.yaml
pyproject.toml

Add repo revew to tephi

---

.pre-commit-config.yaml
docs/source/conf.py
docs/source/plot/barbs.py
pyproject.toml
setup.py

code quality

---

pyproject.toml

Filter warnings

---

pyproject.toml

This pull-request mops up some tech debt to comply with [PEP639](https://peps.python.org/pep-0639/) for `setuptools`, also see [license and license-files](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files).
Additionally avoids the following `setuptools` deprecation warning:
```
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: BSD License
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
```
See [Deprecated license …

pe639: setuptools license and license-files fields
